- hosts: svr5
  remote_user: dev01
  become: yes
  vars:
    v_home_dir: /home/dev01/
    v_base_dir: "{{v_home_dir}}/nvm-work"

  tasks:
  - name: Download microsoft package signature key
    get_url:
      url: https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb
      dest: /tmp/packages-microsoft-prod.deb

  - name: install microsoft package signature key
    script: "{{v_home_dir}}/dpkg-install-mskey.sh"
    args:
      creates: /tmp/mskeyinst.txt

  - name: Install apt-transport-https
    apt:
      name: apt-transport-https
      update_cache: yes

  - name: Install dotnet-sdk-3.1
    apt:
      name: dotnet-sdk-3.1
      update_cache: yes
